version: '3.5'

services:
  cockroach-test:
#   image: christoofar/cockroachdb-arm64:latest
   image: cockroachdb/cockroach:latest
   ports:
     - "26258:26257"
     - "8081:8080"
   command: start-single-node --insecure
   volumes:
     - "cockroach-data-test:/cockroach/cockroach-data"
   restart: unless-stopped
volumes:
 cockroach-data-test: