openapi: 3.0.0
info:
  title: daily-mephi
  version: 1.0.0
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/index.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /index:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/index.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /404:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/404.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /500:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/500.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /about:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/about.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /search:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/search.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /tutors:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/tutors.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /tutors/{id}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/tutors/{id}.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
  /materials:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/materials.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /materials/{id}:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${pages_function_id}
        tag: $latest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
  /quotes/{id}:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${pages_function_id}
        tag: $latest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
  /reviews/{id}:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${pages_function_id}
        tag: $latest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
  /users/{id}:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${pages_function_id}
        tag: $latest
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
  /_next/data/{hash}/tutors/{id}.json:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/_next/data/{hash}/tutors/{id}.json
        presigned_redirect: true
        service_account_id: ${service_account_id}
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: hash
          in: path
          required: true
          schema:
            type: string
  /_next/data/{hash}/materials/{id}.json:
    get:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          application/json: '{"pageProps":{},"__N_SSP":true}'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: hash
          in: path
          required: true
          schema:
            type: string
  /_next/data/{hash}/quotes/{id}.json:
    get:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          application/json: '{"pageProps":{},"__N_SSP":true}'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: hash
          in: path
          required: true
          schema:
            type: string
  /_next/data/{hash}/reviews/{id}.json:
    get:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          application/json: '{"pageProps":{},"__N_SSP":true}'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: hash
          in: path
          required: true
          schema:
            type: string
  /_next/data/{hash}/users/{id}.json:
    get:
      x-yc-apigateway-integration:
        type: dummy
        http_code: 200
        content:
          application/json: '{"pageProps":{},"__N_SSP":true}'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: hash
          in: path
          required: true
          schema:
            type: string
  /api/{path+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - name: path
          in: path
          required: true
          schema:
            type: string

  /{file+}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/{file}
        error_object: static/404.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      parameters:
        - name: file
          in: path
          required: true
          schema:
            type: string
      summary: Serve static file from Yandex Cloud Object Storage
