openapi: 3.0.0
info:
  title: daily-mephi
  version: 1.0.0
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/index.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /404:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/404.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /500:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/500.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /about:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/about.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /index:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/index.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /materials:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/materials.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /profile:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/profile.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /profile/create:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/profile/create.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /tutors:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/tutors.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
  /tutors/{id+}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/tutors/[id].html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
  /users/{id+}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/users/[id].html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      summary: Serve static file from Yandex Cloud Object Storage
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
  /api/{file+}:
    delete:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: file
          required: true
          schema:
            type: string
          style: simple
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: file
          required: true
          schema:
            type: string
          style: simple
    patch:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: file
          required: true
          schema:
            type: string
          style: simple
    post:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: file
          required: true
          schema:
            type: string
          style: simple
    put:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: file
          required: true
          schema:
            type: string
          style: simple
  /{file+}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: daily-mephi
        object: static/{file}
        error_object: static/404.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      parameters:
        - explode: false
          in: path
          name: file
          required: true
          schema:
            type: string
          style: simple
      summary: Serve static file from Yandex Cloud Object Storage
