openapi: 3.0.0
info:
  title: daily-mephi
  version: 1.0.0
paths:
  /:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/index.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
  /{route}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/{route}.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
      parameters:
        - explode: false
          in: path
          pattern: '^tutors|materials|search|about|500|404$'
          name: route
          required: true
          schema:
            type: string
          style: simple
  /tutors/{id}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/{route}/{id}.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
        error_object: static/404.html
      summary: Serve static file from Yandex Cloud Object Storage
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
  /{route}/{id}:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${pages_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
        - explode: false
          in: path
          pattern: '^materials|quotes|reviews|users$'
          name: path
          required: true
          schema:
            type: string
          style: simple
  /_next/data/${hash}/tutors/{id}.json:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/_next/data/${hash}/tutors/{id}.json
        presigned_redirect: true
        service_account_id: ${service_account_id}
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
          style: simple
  /_next/data/${hash}/{path}/{id}.json:
    get:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${pages_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
        - explode: false
          in: path
          pattern: '^materials|quotes|reviews|users$'
          name: path
          required: true
          schema:
            type: string
          style: simple
  /api/v1/{route}/{id}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
        - explode: false
          in: path
          pattern: '^tutors|users|reviews|quotes|news|materials|files$'
          name: route
          required: true
          schema:
            type: string
          style: simple
  /api/v1/{route}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          pattern: '^tutors|users|reviews|quotes|news|materials|files|calculate_score|disciplines|faculties|likes|semesters|top$'
          name: route
          required: true
          schema:
            type: string
          style: simple
  /api/v1/users/{type}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          pattern: '^edit|me$'
          name: type
          required: true
          schema:
            type: string
          style: simple
  /api/v1/comments/{type}/{id}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
        - explode: false
          in: path
          pattern: '^review|material|news$'
          name: type
          required: true
          schema:
            type: string
          style: simple
  /api/auth/{path+}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: path
          required: true
          schema:
            type: string
          style: simple
  /api/v1/comments/{type}/{id}/{comment_id}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
        - explode: false
          in: path
          name: comment_id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
        - explode: false
          in: path
          pattern: '^review|material|news$'
          name: type
          required: true
          schema:
            type: string
          style: simple
  /api/v1/thumbnails/{type}/{id}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
        - explode: false
          in: path
          pattern: '^reviews|materials|quotes|reviews|tutors|users$'
          name: type
          required: true
          schema:
            type: string
          style: simple
  /api/v1/tutors/{id}/{type}:
    x-yc-apigateway-any-method:
      x-yc-apigateway-integration:
        type: cloud-functions
        function_id: ${api_function_id}
        tag: $latest
      parameters:
        - explode: false
          in: path
          name: id
          required: true
          schema:
            type: string
            format: uuid
          style: simple
        - explode: false
          in: path
          pattern: '^reviews|materials|rates|quotes$'
          name: type
          required: true
          schema:
            type: string
          style: simple
  /{file+}:
    get:
      x-yc-apigateway-integration:
        type: object_storage
        bucket: ${bucket_name}
        object: static/{file}
        error_object: static/404.html
        presigned_redirect: true
        service_account_id: ${service_account_id}
      parameters:
        - explode: false
          in: path
          name: file
          required: true
          schema:
            type: string
          style: simple
      summary: Serve static file from Yandex Cloud Object Storage
