-- CreateTable
CREATE TABLE "accounts" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "type" STRING NOT NULL,
    "provider_type" STRING NOT NULL,
    "provider_account_id" STRING NOT NULL,
    "refresh_token" STRING,
    "access_token" STRING,
    "expires_at" INT4,
    "token_type" STRING,
    "scope" STRING,
    "id_token" STRING,
    "session_state" STRING,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "accounts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "sessions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "session_token" STRING NOT NULL,
    "user_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "expires_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "sessions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "users" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "nickname" STRING(50),
    "image_id" UUID,
    "role" STRING NOT NULL DEFAULT 'default',
    "email" STRING,
    "email_verified" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "rating" FLOAT8 NOT NULL DEFAULT 0,
    "bio" STRING(150),
    "place" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "likes_count" INT4 NOT NULL DEFAULT 0,
    "dislikes_count" INT4 NOT NULL DEFAULT 0,
    "comments_count" INT4 NOT NULL DEFAULT 0,
    "materials_count" INT4 NOT NULL DEFAULT 0,
    "reviews_count" INT4 NOT NULL DEFAULT 0,
    "score" FLOAT8 NOT NULL DEFAULT 0,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "verification_tokens" (
    "id" STRING NOT NULL,
    "token" STRING NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3)
);

-- CreateTable
CREATE TABLE "comments" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "text" STRING NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "user_id" UUID NOT NULL,
    "review_id" UUID,
    "material_id" UUID,
    "news_id" UUID,
    "parent_id" UUID,
    "path" STRING[],
    "likes_count" INT4 NOT NULL DEFAULT 0,
    "dislikes_count" INT4 NOT NULL DEFAULT 0,
    "comments_count" INT4 NOT NULL DEFAULT 0,
    "score" FLOAT8 NOT NULL DEFAULT 0,

    CONSTRAINT "comments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "disciplines" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" STRING(400) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "disciplines_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "faculties" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" STRING(200) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "faculties_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "files" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "url" STRING(2000) NOT NULL,
    "alt_url" STRING(2000),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "filename" STRING(500) NOT NULL,
    "user_id" UUID,
    "tutor_id" UUID,
    "material_id" UUID,
    "tag" STRING(200),
    "size" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "files_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "materials" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "text" STRING,
    "title" STRING(280) NOT NULL,
    "user_id" UUID,
    "tutor_id" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "likes_count" INT4 NOT NULL DEFAULT 0,
    "dislikes_count" INT4 NOT NULL DEFAULT 0,
    "comments_count" INT4 NOT NULL DEFAULT 0,
    "score" FLOAT8 NOT NULL DEFAULT 0,

    CONSTRAINT "materials_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "semesters" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" CHAR(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "semesters_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "news" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "text" STRING NOT NULL,
    "title" STRING(280) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "likes_count" INT4 NOT NULL DEFAULT 0,
    "dislikes_count" INT4 NOT NULL DEFAULT 0,
    "comments_count" INT4 NOT NULL DEFAULT 0,

    CONSTRAINT "news_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "quotes" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "text" STRING NOT NULL,
    "tutor_id" UUID NOT NULL,
    "user_id" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "likes_count" INT4 NOT NULL DEFAULT 0,
    "dislikes_count" INT4 NOT NULL DEFAULT 0,
    "score" FLOAT8 NOT NULL DEFAULT 0,

    CONSTRAINT "quotes_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reviews" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "title" STRING(280) NOT NULL,
    "text" STRING NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "legacy_nickname" STRING(200),
    "user_id" UUID,
    "tutor_id" UUID NOT NULL,
    "likes_count" INT4 NOT NULL DEFAULT 0,
    "dislikes_count" INT4 NOT NULL DEFAULT 0,
    "comments_count" INT4 NOT NULL DEFAULT 0,
    "score" FLOAT8 NOT NULL DEFAULT 0,

    CONSTRAINT "reviews_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "reactions" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "user_id" UUID NOT NULL,
    "quote_id" UUID,
    "material_id" UUID,
    "review_id" UUID,
    "comment_id" UUID,
    "news_id" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "like" BOOL NOT NULL,

    CONSTRAINT "reactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "documents" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "words" STRING[],
    "text" STRING NOT NULL,
    "user_id" UUID,
    "tutor_id" UUID,
    "material_id" UUID,
    "review_id" UUID,
    "quote_id" UUID,
    "news_id" UUID,
    "type" STRING NOT NULL DEFAULT 'unknown',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "score" FLOAT8 NOT NULL DEFAULT 0,

    CONSTRAINT "documents_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "tutors" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "first_name" STRING(64),
    "last_name" STRING(64),
    "father_name" STRING(64),
    "full_name" STRING(256) NOT NULL,
    "short_name" STRING(80) NOT NULL,
    "nickname" STRING(64),
    "url" STRING(64),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "reviews_count" INT4 NOT NULL DEFAULT 0,
    "materials_count" INT4 NOT NULL DEFAULT 0,
    "quotes_count" INT4 NOT NULL DEFAULT 0,
    "rates_count" INT4 NOT NULL DEFAULT 0,
    "score" FLOAT8 NOT NULL DEFAULT 0,

    CONSTRAINT "tutors_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rates" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "punctuality" INT4 NOT NULL,
    "personality" INT4 NOT NULL,
    "exams" INT4 NOT NULL,
    "quality" INT4 NOT NULL,
    "tutor_id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "legacy_ratings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "personality" FLOAT8 NOT NULL,
    "personality_count" INT4 NOT NULL,
    "exams" FLOAT8 NOT NULL,
    "exams_count" INT4 NOT NULL,
    "quality" FLOAT8 NOT NULL,
    "quality_count" INT4 NOT NULL,
    "tutor_id" UUID NOT NULL,
    "avg_rating" FLOAT8 NOT NULL,
    "avg_quality" FLOAT8 NOT NULL,
    "avg_personality" FLOAT8 NOT NULL,
    "avg_exams" FLOAT8 NOT NULL,
    "rating_count" INT4 NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "legacy_ratings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ratings" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "punctuality" FLOAT8 NOT NULL,
    "punctuality_count" INT4 NOT NULL,
    "personality" FLOAT8 NOT NULL,
    "personality_count" INT4 NOT NULL,
    "exams" FLOAT8 NOT NULL,
    "exams_count" INT4 NOT NULL,
    "quality" FLOAT8 NOT NULL,
    "quality_count" INT4 NOT NULL,
    "tutor_id" UUID NOT NULL,
    "avg_rating" FLOAT8 NOT NULL,
    "avg_quality" FLOAT8 NOT NULL,
    "avg_personality" FLOAT8 NOT NULL,
    "avg_punctuality" FLOAT8 NOT NULL,
    "avg_exams" FLOAT8 NOT NULL,
    "rating_count" INT4 NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),

    CONSTRAINT "ratings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "internals" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" STRING NOT NULL,
    "value" STRING NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "deleted_at" TIMESTAMP(3),
    "expires_at" TIMESTAMP(3),

    CONSTRAINT "internals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_tutors_disciplines" (
    "A" UUID NOT NULL,
    "B" UUID NOT NULL
);

-- CreateTable
CREATE TABLE "_materials_disciplines" (
    "A" UUID NOT NULL,
    "B" UUID NOT NULL
);

-- CreateTable
CREATE TABLE "_tutors_faculties" (
    "A" UUID NOT NULL,
    "B" UUID NOT NULL
);

-- CreateTable
CREATE TABLE "_materials_faculties" (
    "A" UUID NOT NULL,
    "B" UUID NOT NULL
);

-- CreateTable
CREATE TABLE "_materials_semesters" (
    "A" UUID NOT NULL,
    "B" UUID NOT NULL
);

-- CreateIndex
CREATE INDEX "accounts_type_provider_type_provider_account_id_idx" ON "accounts"("type", "provider_type", "provider_account_id");

-- CreateIndex
CREATE INDEX "accounts_user_id_idx" ON "accounts"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "accounts_provider_type_provider_account_id_key" ON "accounts"("provider_type", "provider_account_id");

-- CreateIndex
CREATE UNIQUE INDEX "sessions_session_token_key" ON "sessions"("session_token");

-- CreateIndex
CREATE INDEX "sessions_user_id_idx" ON "sessions"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "users_nickname_key" ON "users"("nickname");

-- CreateIndex
CREATE UNIQUE INDEX "users_image_id_key" ON "users"("image_id");

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE INDEX "users_rating_idx" ON "users"("rating" DESC);

-- CreateIndex
CREATE UNIQUE INDEX "verification_tokens_token_key" ON "verification_tokens"("token");

-- CreateIndex
CREATE UNIQUE INDEX "verification_tokens_id_token_key" ON "verification_tokens"("id", "token");

-- CreateIndex
CREATE INDEX "comments_created_at_idx" ON "comments"("created_at");

-- CreateIndex
CREATE INDEX "comments_user_id_idx" ON "comments"("user_id");

-- CreateIndex
CREATE INDEX "comments_review_id_idx" ON "comments"("review_id");

-- CreateIndex
CREATE INDEX "comments_material_id_idx" ON "comments"("material_id");

-- CreateIndex
CREATE INDEX "comments_news_id_idx" ON "comments"("news_id");

-- CreateIndex
CREATE INDEX "comments_parent_id_idx" ON "comments"("parent_id");

-- CreateIndex
CREATE INDEX "comments_path_idx" ON "comments" USING GIN ("path");

-- CreateIndex
CREATE UNIQUE INDEX "disciplines_name_key" ON "disciplines"("name");

-- CreateIndex
CREATE UNIQUE INDEX "faculties_name_key" ON "faculties"("name");

-- CreateIndex
CREATE INDEX "files_user_id_idx" ON "files"("user_id");

-- CreateIndex
CREATE INDEX "files_tutor_id_idx" ON "files"("tutor_id");

-- CreateIndex
CREATE INDEX "files_material_id_idx" ON "files"("material_id");

-- CreateIndex
CREATE INDEX "files_created_at_idx" ON "files"("created_at");

-- CreateIndex
CREATE INDEX "materials_created_at_idx" ON "materials"("created_at");

-- CreateIndex
CREATE INDEX "materials_user_id_idx" ON "materials"("user_id");

-- CreateIndex
CREATE INDEX "materials_tutor_id_idx" ON "materials"("tutor_id");

-- CreateIndex
CREATE UNIQUE INDEX "semesters_name_key" ON "semesters"("name");

-- CreateIndex
CREATE INDEX "news_created_at_idx" ON "news"("created_at");

-- CreateIndex
CREATE INDEX "quotes_created_at_idx" ON "quotes"("created_at");

-- CreateIndex
CREATE INDEX "quotes_user_id_idx" ON "quotes"("user_id");

-- CreateIndex
CREATE INDEX "quotes_tutor_id_idx" ON "quotes"("tutor_id");

-- CreateIndex
CREATE INDEX "reviews_created_at_idx" ON "reviews"("created_at");

-- CreateIndex
CREATE INDEX "reviews_user_id_idx" ON "reviews"("user_id");

-- CreateIndex
CREATE INDEX "reviews_tutor_id_idx" ON "reviews"("tutor_id");

-- CreateIndex
CREATE UNIQUE INDEX "reviews_user_id_tutor_id_key" ON "reviews"("user_id", "tutor_id");

-- CreateIndex
CREATE INDEX "reactions_user_id_idx" ON "reactions"("user_id");

-- CreateIndex
CREATE INDEX "reactions_quote_id_idx" ON "reactions"("quote_id");

-- CreateIndex
CREATE INDEX "reactions_material_id_idx" ON "reactions"("material_id");

-- CreateIndex
CREATE INDEX "reactions_review_id_idx" ON "reactions"("review_id");

-- CreateIndex
CREATE INDEX "reactions_comment_id_idx" ON "reactions"("comment_id");

-- CreateIndex
CREATE INDEX "reactions_news_id_idx" ON "reactions"("news_id");

-- CreateIndex
CREATE UNIQUE INDEX "reactions_user_id_quote_id_key" ON "reactions"("user_id", "quote_id");

-- CreateIndex
CREATE UNIQUE INDEX "reactions_user_id_material_id_key" ON "reactions"("user_id", "material_id");

-- CreateIndex
CREATE UNIQUE INDEX "reactions_user_id_review_id_key" ON "reactions"("user_id", "review_id");

-- CreateIndex
CREATE UNIQUE INDEX "reactions_user_id_comment_id_key" ON "reactions"("user_id", "comment_id");

-- CreateIndex
CREATE UNIQUE INDEX "reactions_user_id_news_id_key" ON "reactions"("user_id", "news_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_user_id_key" ON "documents"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_tutor_id_key" ON "documents"("tutor_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_material_id_key" ON "documents"("material_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_review_id_key" ON "documents"("review_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_quote_id_key" ON "documents"("quote_id");

-- CreateIndex
CREATE UNIQUE INDEX "documents_news_id_key" ON "documents"("news_id");

-- CreateIndex
CREATE INDEX "documents_words_idx" ON "documents" USING GIN ("words");

-- CreateIndex
CREATE INDEX "documents_type_idx" ON "documents"("type");

-- CreateIndex
CREATE UNIQUE INDEX "tutors_nickname_key" ON "tutors"("nickname");

-- CreateIndex
CREATE UNIQUE INDEX "tutors_url_key" ON "tutors"("url");

-- CreateIndex
CREATE INDEX "tutors_full_name_idx" ON "tutors"("full_name");

-- CreateIndex
CREATE INDEX "tutors_short_name_idx" ON "tutors"("short_name");

-- CreateIndex
CREATE INDEX "rates_user_id_idx" ON "rates"("user_id");

-- CreateIndex
CREATE INDEX "rates_tutor_id_idx" ON "rates"("tutor_id");

-- CreateIndex
CREATE UNIQUE INDEX "rates_user_id_tutor_id_key" ON "rates"("user_id", "tutor_id");

-- CreateIndex
CREATE UNIQUE INDEX "legacy_ratings_tutor_id_key" ON "legacy_ratings"("tutor_id");

-- CreateIndex
CREATE INDEX "legacy_ratings_tutor_id_idx" ON "legacy_ratings"("tutor_id");

-- CreateIndex
CREATE INDEX "legacy_ratings_personality_idx" ON "legacy_ratings"("personality");

-- CreateIndex
CREATE INDEX "legacy_ratings_personality_count_idx" ON "legacy_ratings"("personality_count");

-- CreateIndex
CREATE INDEX "legacy_ratings_exams_idx" ON "legacy_ratings"("exams");

-- CreateIndex
CREATE INDEX "legacy_ratings_exams_count_idx" ON "legacy_ratings"("exams_count");

-- CreateIndex
CREATE INDEX "legacy_ratings_quality_idx" ON "legacy_ratings"("quality");

-- CreateIndex
CREATE INDEX "legacy_ratings_quality_count_idx" ON "legacy_ratings"("quality_count");

-- CreateIndex
CREATE INDEX "legacy_ratings_avg_rating_idx" ON "legacy_ratings"("avg_rating");

-- CreateIndex
CREATE INDEX "legacy_ratings_rating_count_idx" ON "legacy_ratings"("rating_count");

-- CreateIndex
CREATE UNIQUE INDEX "ratings_tutor_id_key" ON "ratings"("tutor_id");

-- CreateIndex
CREATE INDEX "ratings_tutor_id_idx" ON "ratings"("tutor_id");

-- CreateIndex
CREATE INDEX "ratings_personality_idx" ON "ratings"("personality");

-- CreateIndex
CREATE INDEX "ratings_personality_count_idx" ON "ratings"("personality_count");

-- CreateIndex
CREATE INDEX "ratings_punctuality_idx" ON "ratings"("punctuality");

-- CreateIndex
CREATE INDEX "ratings_punctuality_count_idx" ON "ratings"("punctuality_count");

-- CreateIndex
CREATE INDEX "ratings_exams_idx" ON "ratings"("exams");

-- CreateIndex
CREATE INDEX "ratings_exams_count_idx" ON "ratings"("exams_count");

-- CreateIndex
CREATE INDEX "ratings_quality_idx" ON "ratings"("quality");

-- CreateIndex
CREATE INDEX "ratings_quality_count_idx" ON "ratings"("quality_count");

-- CreateIndex
CREATE INDEX "ratings_avg_rating_idx" ON "ratings"("avg_rating");

-- CreateIndex
CREATE INDEX "ratings_rating_count_idx" ON "ratings"("rating_count");

-- CreateIndex
CREATE UNIQUE INDEX "internals_name_key" ON "internals"("name");

-- CreateIndex
CREATE INDEX "internals_name_idx" ON "internals"("name");

-- CreateIndex
CREATE UNIQUE INDEX "_tutors_disciplines_AB_unique" ON "_tutors_disciplines"("A", "B");

-- CreateIndex
CREATE INDEX "_tutors_disciplines_B_index" ON "_tutors_disciplines"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_materials_disciplines_AB_unique" ON "_materials_disciplines"("A", "B");

-- CreateIndex
CREATE INDEX "_materials_disciplines_B_index" ON "_materials_disciplines"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_tutors_faculties_AB_unique" ON "_tutors_faculties"("A", "B");

-- CreateIndex
CREATE INDEX "_tutors_faculties_B_index" ON "_tutors_faculties"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_materials_faculties_AB_unique" ON "_materials_faculties"("A", "B");

-- CreateIndex
CREATE INDEX "_materials_faculties_B_index" ON "_materials_faculties"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_materials_semesters_AB_unique" ON "_materials_semesters"("A", "B");

-- CreateIndex
CREATE INDEX "_materials_semesters_B_index" ON "_materials_semesters"("B");

-- AddForeignKey
ALTER TABLE "accounts" ADD CONSTRAINT "accounts_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "users" ADD CONSTRAINT "users_image_id_fkey" FOREIGN KEY ("image_id") REFERENCES "files"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_news_id_fkey" FOREIGN KEY ("news_id") REFERENCES "news"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "comments" ADD CONSTRAINT "comments_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "comments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- AddForeignKey
ALTER TABLE "files" ADD CONSTRAINT "files_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "tutors"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "files" ADD CONSTRAINT "files_uploaded_by_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "files" ADD CONSTRAINT "files_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "materials" ADD CONSTRAINT "materials_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "materials" ADD CONSTRAINT "materials_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "quotes" ADD CONSTRAINT "quotes_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reactions" ADD CONSTRAINT "reactions_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reactions" ADD CONSTRAINT "reactions_quote_id_fkey" FOREIGN KEY ("quote_id") REFERENCES "quotes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reactions" ADD CONSTRAINT "reactions_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reactions" ADD CONSTRAINT "reactions_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reactions" ADD CONSTRAINT "reactions_comment_id_fkey" FOREIGN KEY ("comment_id") REFERENCES "comments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "reactions" ADD CONSTRAINT "reactions_news_id_fkey" FOREIGN KEY ("news_id") REFERENCES "news"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_material_id_fkey" FOREIGN KEY ("material_id") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_review_id_fkey" FOREIGN KEY ("review_id") REFERENCES "reviews"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_quote_id_fkey" FOREIGN KEY ("quote_id") REFERENCES "quotes"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "documents" ADD CONSTRAINT "documents_news_id_fkey" FOREIGN KEY ("news_id") REFERENCES "news"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rates" ADD CONSTRAINT "rates_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "rates" ADD CONSTRAINT "rates_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "legacy_ratings" ADD CONSTRAINT "legacy_ratings_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ratings" ADD CONSTRAINT "ratings_tutor_id_fkey" FOREIGN KEY ("tutor_id") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_tutors_disciplines" ADD CONSTRAINT "_tutors_disciplines_A_fkey" FOREIGN KEY ("A") REFERENCES "disciplines"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_tutors_disciplines" ADD CONSTRAINT "_tutors_disciplines_B_fkey" FOREIGN KEY ("B") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_materials_disciplines" ADD CONSTRAINT "_materials_disciplines_A_fkey" FOREIGN KEY ("A") REFERENCES "disciplines"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_materials_disciplines" ADD CONSTRAINT "_materials_disciplines_B_fkey" FOREIGN KEY ("B") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_tutors_faculties" ADD CONSTRAINT "_tutors_faculties_A_fkey" FOREIGN KEY ("A") REFERENCES "faculties"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_tutors_faculties" ADD CONSTRAINT "_tutors_faculties_B_fkey" FOREIGN KEY ("B") REFERENCES "tutors"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_materials_faculties" ADD CONSTRAINT "_materials_faculties_A_fkey" FOREIGN KEY ("A") REFERENCES "faculties"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_materials_faculties" ADD CONSTRAINT "_materials_faculties_B_fkey" FOREIGN KEY ("B") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_materials_semesters" ADD CONSTRAINT "_materials_semesters_A_fkey" FOREIGN KEY ("A") REFERENCES "materials"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_materials_semesters" ADD CONSTRAINT "_materials_semesters_B_fkey" FOREIGN KEY ("B") REFERENCES "semesters"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE INDEX "documents_text_idx" ON "documents" USING GIN("text" gin_trgm_ops);
