name: 'Test and deploy'
on: push
env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL }}
jobs:
  # jest:
  #   name: 'Jest tests'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Install modules
  #       run: yarn
  #     - name: Run tests
  #       run: yarn test
#  chromatic:
#    name: 'Chromatic Deployment'
#    # Operating System
#    runs-on: ubuntu-latest
#    # Job steps
#    steps:
#      - uses: actions/checkout@v1
#      - run: yarn
#        #👇 Adds Chromatic as a step in the workflow
#      - uses: chromaui/action@v1
#        # Options required for Chromatic's GitHub Action
#        with:
#          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/ to obtain it
#          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
#          token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: 'Deploy on cloud'
    if: ${{ github.ref == 'refs/heads/main' }}
#    needs: [ jest, chromatic ]
    # needs: [ jest ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Pull Terraform CLI
        uses: hashicorp/setup-terraform@v2
      - name: Add .terraformrc
        run: echo 'provider_installation {
            network_mirror {
            url = "https://terraform-mirror.yandexcloud.net/"
            include = ["registry.terraform.io/*/*"]
          }
          direct {
            exclude = ["registry.terraform.io/*/*"]
          }
          }' > ~/.terraformrc
      - name: Configure AWS Credentials
        run: |
          rm -rf ~/.aws
          mkdir -p ~/.aws
          echo '[default]
            aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}' > ~/.aws/credentials
          echo '[default]
            region=ru-central1' > ~/.aws/config

      - name: Install Yandex Cloud CLI
        run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash

      - name: Add Yandex Cloud CLI to $PATH
        run: echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Init Yandex Cloud CLI
        run: |
          yc config profile create github-actions
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          yc config set token ${{ secrets.YC_TOKEN }}
      

      - name: Install vercel CLI
        run: npm install --global vercel@latest
      - name: Run Terraform Apply
        run: |
          cd terraform
          chmod +x hash.sh
          terraform init \
          -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          terraform apply -input=false --auto-approve
        env:
          TF_VAR_token : ${{secrets.TF_VAR_TOKEN}}
          TF_VAR_cloud_id : ${{secrets.TF_VAR_CLOUD_ID}}
          TF_VAR_folder_id : ${{secrets.TF_VAR_FOLDER_ID}}
          TF_VAR_zone : ${{secrets.TF_VAR_ZONE}}

          TF_VAR_DATABASE_URL : ${{secrets.TF_VAR_DATABASE_URL}}
          TF_VAR_LOCAL : ${{secrets.TF_VAR_LOCAL}}

          TF_VAR_DOMAIN_ID: ${{secrets.TF_VAR_DOMAIN_ID}}

          TF_VAR_NEXTAUTH_SECRET : ${{secrets.TF_VAR_NEXTAUTH_SECRET}}
          TF_VAR_HASH_SECRET : ${{secrets.TF_VAR_HASH_SECRET}}
          TF_VAR_HASH_SALT : ${{secrets.TF_VAR_HASH_SALT}}
          TF_VAR_HASH_MEMORY_COST : ${{secrets.TF_VAR_HASH_MEMORY_COST}}
          TF_VAR_HASH_TYPE : ${{secrets.TF_VAR_HASH_TYPE}}
          TF_VAR_HASH_TIME_COST : ${{secrets.TF_VAR_HASH_TIME_COST}}
          TF_VAR_HASH_PARALLELISM : ${{secrets.TF_VAR_HASH_PARALLELISM}}
          TF_VAR_AES_NONCE : ${{secrets.TF_VAR_AES_NONCE}}
          TF_VAR_AES_KEY256 : ${{secrets.TF_VAR_AES_KEY256}}
          TF_VAR_NEXTAUTH_URL : ${{secrets.TF_VAR_NEXTAUTH_URL}}
          TF_VAR_JWT_PRIVATE : ${{secrets.TF_VAR_JWT_PRIVATE}}
          TF_VAR_NOTION_TOKEN : ${{secrets.TF_VAR_NOTION_TOKEN}}
          TF_VAR_NOTION_PRIVATE_PAGE : ${{secrets.TF_VAR_NOTION_PRIVATE_PAGE}}
          TF_VAR_NOTION_TOKEN_V2 : ${{secrets.TF_VAR_NOTION_TOKEN_V2}}
          TF_VAR_NOTION_EMAIL : ${{secrets.TF_VAR_NOTION_EMAIL}}
          TF_VAR_NOTION_PASSWORD : ${{secrets.TF_VAR_NOTION_PASSWORD}}
          TF_VAR_RECAPTCHA_SECRET : ${{secrets.TF_VAR_RECAPTCHA_SECRET}}
          TF_VAR_RECAPTCHA_PUBLIC : ${{secrets.TF_VAR_RECAPTCHA_PUBLIC}}
          TF_VAR_DATABASE_KEY : ${{secrets.TF_VAR_DATABASE_KEY}}

          TF_VAR_VERCEL_TOKEN : ${{secrets.TF_VAR_VERCEL_TOKEN}}
          TF_VAR_GOOGLE_API_KEY : ${{secrets.TF_VAR_GOOGLE_API_KEY}}
          TF_VAR_certificate_id : ${{secrets.TF_VAR_CERTIFICATE_ID}}
